name: Linting

on:
  push:
    branches:
      - staging
      - production

jobs:
  lint:
    name: Run Linting
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Set the Node.js version you need

      - name: Install Dependencies
        working-directory: ./app
        run: pnpm install

      - name: Run Linting
        working-directory: ./app
        run: pnpm lint
